### ISSUE TITLE
Non-Functional Repository

### ISSUE THREAD

**Issue by resolutedreamer** [jpf/Twilio-TFA#1]
Hi,

Following the instructions in the README do not work in Ubuntu 15.04. There is an error with PIL 1.1.7. Please help.

Thanks!

**Comment by jpf** [comment]
Hey there, I'm sorry to hear that. I'm no longer working at Twilio and unfortunately I don't have the bandwidth to maintain this repository any longer. I suggest reaching out to Twilio and seeing if you can get connected with someone who could help.
